# Generated by Django 4.2.3 on 2023-07-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_user_password_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dp',
            field=models.FileField(upload_to='custom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
